### PR TITLE
Bug fix get_leaf(); fixes #40

### LINKED ISSUE #40: drive_mkdir doesn't allow for multiple folders with the same name in the same path
as mentioned in #24 
I think there may be a small bug in the get_leaf function - when I run:
```
drive_mkdir("baz", path = "test_8675309/foo/yo")
```
I see
```
## Error: The path 'test_8675309/foo/yo/' identifies more than one file:
## File of type folder, with id 0B0Gh-SuuA2nTOEVQX1BteW1Fa3M.
## File of type folder, with id 0B0Gh-SuuA2nTN3VMYWdOZlhrM0k.
```
but on drive I have:
test_8675309
+-- foo
| +-- yo (id 0B0Gh-SuuA2nTOEVQX1BteW1Fa3M)
+-- yo (id 0B0Gh-SuuA2nTN3VMYWdOZlhrM0k)

so in fact test_8675309/foo/yo should be unique (since the other one that it's fussing about is actually test_8675309/yo)

Also, when checking through the path, match [here](https://github.com/tidyverse/googledrive/blob/master/R/drive_path.R#L33) doesn't allow for nested folders with the same name. For example if we had "foo/foo", which is perfectly logical, match only matches the first, so we would have depth 1 for both, where they should each be listed as both depth 1 and 2.

### PR DESCRIPTION
**Pull request by jennybc**
This is a fix for #40 based on path length.

I still need to address this point from #40 and will borrow your approach from #41.

> Also, when checking through the path, match here doesn't allow for nested folders with the same name. For example if we had "foo/foo", which is perfectly logical, match only matches the first, so we would have depth 1 for both, where they should each be listed as both depth 1 and 2.

### CODE REVIEW

**Comment by jennybc** [comment]
> I think this will still cause a problem

See what you think now. I reworked things a bit.

File: R/drive_path.R [hunk 1]
```diff
@@ -30,39 +30,44 @@ get_leaf <- function(path = NULL) {
   ## guarantee: we have found at least one item with correct name for
   ## each piece of path
 
-  hits$depth <- match(hits$name, path_pieces)
-  hits <- hits[order(hits$depth), ]
-
   ## leaf candidate(s)
-  leaf_id <- hits$id[hits$depth == d]
+  leaf_id <- hits$id[hits$name == last(path_pieces)]
```
Comment (jennybc) [inline R/drive_path.R]: I think this is going to generalize better to case where we need to loop backwards over path pieces, until we find one that actually exists.

Comment (LucyMcGowan) [inline R/drive_path.R]: oh lovely! it works! 🎉

**Comment by jennybc** [comment]
Please have one last look.I removed a lot of tests that seemed redundant. I think this fixes the problems you spotted (foo/bar vs bar, foo/foo) and at least one new one I discovered along the way (foo/bar/baz vs bar/foo/baz). If you think looks ok, let's merge.

**Comment by LucyMcGowan** [comment]
looks good to me 👍
